// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }




    
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiOCCiE6jX0oTTWzj5-E6hG6Gd_MpKy1E',
    appId: '1:92319697135:web:e2846edf412057d88a731a',
    messagingSenderId: 'e2846edf412057d88a731a',
    projectId: 'playercollector-724d2',
    authDomain: 'playercollector-724d2.firebaseapp.com',
    storageBucket: 'playercollector-724d2.firebasestorage.app',
    measurementId: 'G-C4WSS1KN7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCULOzZ2NkCHMolRo1OauufkTfJShIsr2c',
    appId: '1:92319697135:android:1e0c5665358a26ab8a731a',
    messagingSenderId: '1e0c5665358a26ab8a731a',
    projectId: 'playercollector-724d2',
    storageBucket: 'playercollector-724d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT3x_bBhO7jjuwbRwIqX-ZB_Xtofi7krU',
    appId: '1:92319697135:ios:53cf74259c2287278a731a',
    messagingSenderId: '53cf74259c2287278a731a',
    projectId: 'playercollector-724d2',
    storageBucket: 'playercollector-724d2.firebasestorage.app',
    iosBundleId: 'com.example.playerCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT3x_bBhO7jjuwbRwIqX-ZB_Xtofi7krU',
    appId: '1:92319697135:ios:53cf74259c2287278a731a',
    messagingSenderId: '53cf74259c2287278a731a',
    projectId: 'playercollector-724d2',
    storageBucket: 'playercollector-724d2.firebasestorage.app',
    iosBundleId: 'com.example.playerCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiOCCiE6jX0oTTWzj5-E6hG6Gd_MpKy1E',
    appId: '1:92319697135:web:82d63d1012b6894f8a731a',
    messagingSenderId: '82d63d1012b6894f8a731a',
    projectId: 'playercollector-724d2',
    authDomain: 'playercollector-724d2.firebaseapp.com',
    storageBucket: 'playercollector-724d2.firebasestorage.app',
    measurementId: 'G-Q2741HFYMG',
  );


  
}
